### PR TITLE
Do not automatically open serialport

### LINKED ISSUE #4: "Port is opening" - when using RTU
Apparently, `new SerialPort(...)` will automatically open the port unless adding option `autoOpen: false`. Since modbus-serial is also opening this port we seem to get `Port is opening` and app bails out.

I'm in a bit of a hurry but I simply tried to add `autoOpen: false` to the options object but it didn't seem to have any effect unfortunately. Maybe this is actually caused because of something else?

### PR DESCRIPTION
**Pull request by pakerfeldt**
Closes #4

### CODE REVIEW

**Comment by yaacov** [comment]
This will not work on current version of serialport :-(
https://github.com/EmergingTechnologyAdvisors/node-serialport#new_module_serialport--SerialPort_new

can you think of a way that will also work on newer versions ?

**Comment by pakerfeldt** [comment]
As Long as this project states the dependency as `^2.0.5` I don't see a reason to support the new way of specifying options to serial port?

**Comment by yaacov** [comment]
I see ...
https://github.com/yaacov/node-modbus-ws/blob/master/package.json#L34

we can update that to 4 as of
https://github.com/yaacov/node-modbus-serial/pull/35

and then it will be autoOpen

**Comment by yaacov** [comment]
we should also update modbus serial ... version ...

**Comment by yaacov** [comment]
so ....
I will merge this one, ... and update dependences in a new PR, and then also revisit the autoopen thing ...

thanks for noticing this 👍 

p.s.
If youcan do the update dependences it will happen faster :-)

**Pull request merged**
